[technote]
id = "RTN-094"
series_id = "RTN"
canonical_url = "https://rtn-094.lsst.io"
github_url = "https://github.com/lsst/rtn-094"
github_default_branch = "main"
date_created = 2025-03-06T15:23:54Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Leanne P."
name.family = "Guy"
internal_id = "guylp"
orcid = "https://orcid.org/0000-0003-0800-8755"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
