---
title: "Eng-Ops Planning"
---
%%{ init: { "theme": "default", "themeVariables": { "fontSize": "24px"} } }%%
flowchart TB
Quarterly --> Monthly
 Monthly --> Weekly
  Weekly --> Daily
subgraph Quarterly [Yearly→Quarterly]
   direction TB
   Q0@{ shape: notch-rect, label: "Chief Engineer"}
   Q1["Daytime Quarterly Review"]
   Q0 --> Q1
   end
subgraph Monthly
   direction TB
   M0@{ shape: notch-rect, label: "Observatory Scientist"}
   M1["Summit Monthly Planning"]
   M4@{ shape: pill, label: Confluence meeting notes}
   click M4 "https://rubinobs.atlassian.net/wiki/spaces/LSSTPO/pages/43244380/St
rategic+Planning+Meeting"
   M0 --> M1
   M1 --> M4
   end 
subgraph Weekly
   direction TB
   W0@{ shape: notch-rect, label: "Summit Manager"}
   W1[Daytime Weekly Integration]
   W2@{ shape: pill, label: Summit calendars }
   click W2 "https://rubinobs.atlassian.net/plugins/servlet/ac/doitbetter.calend
ar/calendar-page?project.key=SUMMIT&project.id=10053"
   W0 --> W1
   W1 --> W2
   M5@{ shape: notch-rect, label: "Systems Support Scientist"}
   M2["Weekly Summit Performance Status"]
   M3@{ shape: pill, label: Week test plan}
   click M3 "https://rubinobs.atlassian.net/wiki/spaces/LSSTCOM/pages/53741775/S
ITCOM+Test+Planning+STP"
   M5 --> M2
   M2 --> M3
   end
subgraph Daily
   direction TB
   D0@{ shape:  notch-rect, label: "Deputy Summit Manager"}
   D1[Daytime Briefing]
   D2@{ shape: pill, label: "#Summit announce" }
   D0 --> D1
   D1 --> D2
   end
